# Generated by Django 3.0.8 on 2020-07-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_App', '0003_auto_20200717_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(to='django_App.tag'),
        ),
    ]
