# Generated by Django 3.0.8 on 2020-07-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_App', '0004_auto_20200717_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(to='django_App.tag'),
        ),
    ]
