# Generated by Django 3.0.8 on 2020-07-17 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_App', '0005_auto_20200717_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_App.Products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('outdor', 'outdoor'), ('indoor', 'indoor')], max_length=100, null=True),
        ),
    ]
