# Generated by Django 3.0.8 on 2020-07-17 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_App', '0007_auto_20200717_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_App.Customers'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_App.Products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='tags',
            field=models.ManyToManyField(to='django_App.Tag'),
        ),
    ]
