# Generated by Django 3.0.8 on 2020-07-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_App', '0009_auto_20200720_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='django_App.Tag'),
        ),
    ]
